package Network;

public enum CommandTypes {
    BUY_FROM_MARKET,
    SELL_TO_MARKET,
    SEND_MASSAGE,
    SEND_PLAYER,
    UPDATE_MARKET,
    SEND_LEADER_BOARD,
    SEND_LIST,
    PLAYER_JOINED,
    PLAYER_EXITED,
    SERVER_EXITED,
    VIEW_PROFILE,
    PRIVATE_CHAT,
    SEND_INDIVIDUAL_MESSAGE,
    SEND_WILD_ANIMAL;
}
