package Network;

public enum CommandTypes {
    BUY_FROM_MARKET,
    SELL_TO_MARKET,
    SEND_MASSAGE,
    SEND_PLAYER,
    UPDATE_MARKET_ADD,
    UPDATE_MARKET_REMOVE,
    SEND_LEADER_BOARD,
    SEND_MARKET,
    SEND_LIST,
    PLAYER_JOINED,
    PLAYER_EXITED,
    SERVER_EXITED,
    VIEW_PROFILE,
    PRIVATE_CHAT,
    SEND_INDIVIDUAL_MESSAGE,
    SEND_WILD_ANIMAL,
    APPROVE_REQUEST,
    SEND_FRIEND_REQUEST,
    SEND_LEVEL,
    SEND_MONEY,
    UPDATE_LEVEL,
    UPDATE_MONEY;
}
